export const dataVue = {
  versionNumber: "2.6.7",
  currentYear: '',
  countriesList: [],
  countiresData: [],
  defaultCountry: "Myanmar",
  title: false,
  notFound: false,
  inWord: false,
  loading: false,
  dataText: false,
  date: "",
  country: "",
  cases: "",
  todayCases: "",
  active: "",
  recovered: "",
  totalDeaths: "",
  todayDeaths: "",
  totalTests: "",
  critical: "",
  flagSrc: "",
  profileHref: "https://www.facebook.com/leonzifer"
};