export const searchDataVue = {
  countriesList: [],
  countiresData: [],
  defaultCountry: "Myanmar",
  title: false,
  notFound: false,
  inWord: false,
  loading: false,
  dataText: false,
  date: "",
  country: "",
  cases: "",
  todayCases: "",
  active: "",
  recovered: "",
  totalDeaths: "",
  todayDeaths: "",
  totalTests: "",
  critical: "",
  flagSrc: ""
};
